spring.application.name=demoPostGre

spring.datasource.url="postgresql://my_demo_posgre_user:RD6hVlIflgqOC6IYH1GBPf3vZAXnMtbH@dpg-d9jor7gu01pc73fkp9c0-a/my_demo_posgre"
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}