spring.application.name=demoPostGre
spring.datasource.url=jdbc:postgresql://localhost:5432/demoPostgre
spring.datasource.username=postgres
spring.datasource.password=545312
spring.jpa.hibernate.ddl-auto=update
server.port=8080